config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'payments/new'

  resources :conversations do
    resources :messages
  end

  get '/profile' => 'pages#profile'
  get '/about' => 'pages#about'


  resource :operator_profiles, only: [:edit, :update, :show]
  resources :operator_profiles, only: [:show]

  resources :images, only: :destroy

  resources :requests do
    resources :proposals, only: [:create, :new]
  end

  resources :proposals, except: [:new] do
      resources :reviews
      member do
        post 'accept', to: "proposals#accept"
        post 'decline', to: "proposals#decline"
      end
      resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#index"
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  def belongs_to(user)
    (sender_id == user.id) || (recipient_id == user.id)
  end

  def messages_for(user)
    messages.where.not(user_id: user.id)
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :operator_profile

  mount_uploader :image, ImageUploader

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
    belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%d/%m/%y at %l:%M %p")
  end

  def set_to_read
    self.read = true
    self.save
  end

  def self.read
    where(read: true)
  end

  def self.unread
    where(read: false)
  end

end

app/models/operator_profile.rb
class OperatorProfile < ApplicationRecord
  belongs_to :user
  has_many :videos, dependent: :destroy
  has_many :operator_skills, dependent: :destroy
  has_many :skills, through: :operator_skills
  has_many :images, dependent: :destroy

  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :images, :videos, allow_destroy: true, reject_if: :all_blank

end

app/models/operator_skill.rb
class OperatorSkill < ApplicationRecord
  belongs_to :operator_profile
  belongs_to :skill
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  belongs_to :request
  has_one :review, dependent: :destroy

  validates :price, presence: true
  validates :content, presence: true
  monetize :price_cents
  enum status: [:pending, :rejected, :accepted, :paid]
  #?
  #!
  #
  after_create :send_proposal_submitted_email

    def accept
      self.accepted!
      self.request.close
    end

    def created_by(user)
      user_id == user.id
    end


  private

    def send_proposal_submitted_email
      ProposalMailer.proposal_submitted(self).deliver_now
    end


end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy

  CATEGORIES = %w(marketing event architectural)
  validates :location, presence: true
  validates :due_date, presence: true
  validates :category, inclusion: {in: CATEGORIES}
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
  enum status: [:open, :closed]

  after_create :send_request_created_email

  def close
    self.closed!
    self.proposals.pending.each do |proposal|
      proposal.rejected!
    end
  end

  def created_by(user)
    user_id == user.id
  end

  private

  def send_request_created_email
    RequestMailer.request_created(self).deliver_now
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :proposal

  validates :content, presence: true
  validates :rating, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :operator_skills, dependent: :destroy
  validates :name, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, PhotoUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true



  has_one :operator_profile, dependent: :destroy

  has_many :requests, dependent: :destroy
  has_many :pending_proposals, through: :requests, source: :proposals #All proposals on user's requests
  has_many :proposals, dependent: :destroy #Created by this user
  has_many :messages
  has_many :created_conversations, dependent: :destroy, foreign_key: :sender_id, class_name: 'Conversation'
  has_many :joined_conversations, dependent: :destroy, foreign_key: :recipient_id, class_name: 'Conversation'
  has_many :images, through: :operator_profiles
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  after_create :send_welcome_email
  after_create :create_op_profile, if: "self.pilot?"

  def not_applied?(request)
    self.proposals.find_by(request_id: request.id).nil?
  #is there a proposal from the current_user for a specific request
  end

  def create_op_profile
    self.create_operator_profile
  end

  def unread_messages?
    Message.unread.joins(:conversation).where("(conversations.sender_id = :id OR conversations.recipient_id = :id)", id: self.id).where.not(user_id: self.id).any?
  end

  private

  def send_welcome_email
    if self.pilot?
      UserMailer.welcome_pilot(self).deliver_now
    else
      UserMailer.welcome_client(self).deliver_now
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :operator_profile

  # validates :url, presence: true
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>

    <title>DroneIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= javascript_include_tag 'dist/js/smooth-scroll' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Orbitron:400,500'; %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dynamic tabs</title>
    <meta name=“description“ content="We provide the easiest way to find a drone pilot for your personal needs. The pilots of our platform are certified and provide aerial images for all types of business. They have experience in construction, real estate, events and many more." />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="Droneit - Hire a drone pilot fast and easy!" />
    <meta property="og:description"        content="We provide the easiest way to find a drone pilot for your personal needs. The pilots of our platform are certified and provide aerial images for all types of business. They have experience in construction, real estate, events and many more." />

  </head>

  <body class='<%= "#{controller_name} #{action_name}" %>'>
      <%= render 'shared/flashes' %>
      <%= render "shared/navbar" %>
      <%= yield %>
      <%= render 'shared/footer' %>

      <!--<link rel="stylesheet" href="src/css/swipebox.css"> -->
      <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV["GOOGLE_API_SERVER_KEY"]}" %>
      <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
      <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
      <%= javascript_include_tag 'application' %>
      <%#= javascript_include_tag 'src/js/jquery.swipebox.js' %>

      <%= yield(:after_js) %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" >
    <div class="text-center">
      <h3 class="orbitron" style="font-size: 30px">Droneit</h3>
    </div>
    <div class="text-center">
      <div class="inline">
          <%= link_to "Contact us |", '#', class: "footerlinks white" %>
      </div>
      <div class="inline">
          <%= link_to " Terms of use |", '#', class: "footerlinks white" %>
      </div>
      <div class="inline">
          <%= link_to " Privacy |", '#', class: "footerlinks white" %>
      </div>
      <div class="inline">
          <%= link_to " Help", '#', class: "footerlinks white" %>
      </div>

      <div class="divider">
        <div class='inline'>
          <a href="#"> <i class="fa fa-facebook white"> </i> </a>
        </div>
        <div class="inline">
          <a href=""> <i class="fa fa-envelope-o white"> </i> </a>
        </div>
        <div class='inline'>
          <a href="#"> <i class="fa fa-instagram white"> </i> </a>
        </div>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<span id="top"></span>

<nav class='navbar navbar-default <%= "navbar-home" if current_page?(root_path) %>'>
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="float-left logo">
        <%= image_tag "logo.png", width: '60px' %>
      </div>
      <div class="float-left">
        <%= link_to "Droneit", root_path, class: "navbar-brand" %>
      </div>
    </div><!-- /navbar-header -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">

      <% unless user_signed_in? %>
        <li><%= link_to "Sign up as a Client", new_user_registration_path(as:"client"), class: 'navbar-link' %></li>
        <li><%= link_to "Sign up as a Pilot", new_user_registration_path(as:"pilot"), class: 'navbar-link' %></li>
        <li><%= link_to "Log in", new_user_session_path, class: 'navbar-link' %></li>
      <% end %>

      <% if user_signed_in? && current_user.avatar_url %>
        <%= image_tag current_user.avatar, height: 50, width: 51 %>
      <% elsif user_signed_in? && !current_user.avatar_url %>
        <%= image_tag "avatar_default.jpg", height: 50, width: 51 %>
      <% end %>

      <% if user_signed_in? && current_user.pilot? %>
        <li> <%= link_to "Proposals", proposals_path, class: 'otherlinks' %> </li>
        <li> <%= link_to "Requests", requests_path, class: 'otherlinks' %></li>
        <li>
          <%= link_to conversations_path, class: 'otherlinks' do %>
          <i class="fa fa-envelope-o"></i> Messages<% end %>
        </li>
      <% elsif user_signed_in? %>
        <li> <%= link_to "Requests", requests_path, class: 'otherlinks' %></li>
        <li> <%= link_to conversations_path, class: 'otherlinks' do %>
          <i class="fa fa-envelope-o"></i> Messages
          <% if current_user.unread_messages? %>
           <i class='fa fa-bell'></i></li>
           <% end %>
        <% end %>
      <% end %>

      <% if user_signed_in? %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Profile", profile_path %></li>
            <% if current_user.pilot? %>
            <% if current_user.operator_profile(current_user.id) %>
            <li> <%= link_to "Operator Profile", operator_profile_path(current_user.operator_profile) %> </li>
            <% else %>
            <li> <%= link_to "Operator Profile", new_operator_profile_path %> </li>
            <% end %>
            <% end %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>