config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'payments/new'

  resources :conversations do
    resources :messages
  end

  get '/profile' => 'pages#profile'
  get '/about' => 'pages#about'


  resource :operator_profiles, only: [:edit, :update, :show]
  resources :operator_profiles, only: [:show]

  resources :images, only: :destroy

  resources :requests do
    resources :proposals, only: [:create, :new]
  end

  resources :proposals, except: [:new] do
      resources :reviews
      member do
        post 'accept', to: "proposals#accept"
        post 'decline', to: "proposals#decline"
      end
      resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#index"
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy

  CATEGORIES = %w(marketing event architectural)
  validates :location, presence: true
  validates :due_date, presence: true
  validates :category, inclusion: {in: CATEGORIES}
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
  enum status: [:open, :closed]

  after_create :send_request_created_email

  def close
    self.closed!
    self.proposals.pending.each do |proposal|
      proposal.rejected!
    end
  end

  def created_by(user)
    user_id == user.id
  end

  private

  def send_request_created_email
    RequestMailer.request_created(self).deliver_now
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:edit, :update, :destroy]

  def index
    if current_user.pilot
      @requests = Request.open
    else
      @requests = current_user.requests
    end
  end

  def show
    @request = Request.find_by(id: params[:id])
    @request_coordinates = { lat: @request.latitude, lng: @request.longitude }

    @hash = Gmaps4rails.build_markers(@request) do |request, marker|
      marker.lat request.latitude
      marker.lng request.longitude
      # marker.infowindow render_to_string(partial: "/requests/map_box", locals: { request: request })
    end
    redirect_to root_path if !@request.created_by(current_user) && !current_user.pilot?
  end

  def new
    @request = Request.new
  end

  def create
    if current_user.pilot
      redirect_to root_path
    else
      @request = current_user.requests.create(request_params)
      flash[:notice] = "Your request has been created"
      redirect_to requests_path
    end
  end

  def edit
  end

  def update
    authorize @request
    @request.update(request_params)
    redirect_to request_path(@request)
  end

  def destroy
    authorize @request
    @request.destroy
    redirect_to requests_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      if current_user
        @request = current_user.requests.find_by(id: params[:id])
      else
        redirect_to root_path
      end
    end

    # Only allow a trusted parameter "white list" through.
    def request_params
      params.require(:request).permit(:due_date, :location, :details, :category)
    end
end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/requests/_form.html.erb
<div class="form_container">
<%= simple_form_for @request do |f| %>
  <div class="form">
    <p> Until when do you need your drone images? </p>
    <%= f.input :due_date, required: true, autofocus: true, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' }  %>
    <%= f.input :location, required: true, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' }  %>
    <p> Do you have any special requests? </p>
    <%= f.input :details, as: :text, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' }  %>
    <p> What do you need the aerial images or videos for? </p>
    <%= f.input :category, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' }  do %>
      <%= f.select :category, Request::CATEGORIES %>
    <%= f.input :status, as: :hidden, input_html: { :value => '0' } %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'form-btn' %>
  </div>
<% end %>
</div>

app/views/requests/edit.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-6 col-md-offset-3 footer-container'>
    <div class="form">
      <h1>Edit request for a Drone Pilot</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<!-- List of all Requests the current user made -->

<div class="container">
  <div class="requests footer-container">
    <%if !current_user.pilot %>
      <h1>These are your requests</h1>
      <p>Manage your requests here</p>
    <% else %>
      <h1>These are all open requests</h1>
      <p>Make a proposal here</p>
    <% end %>

    <table class= "table table-hover">
      <thead>
        <tr>
          <th><p><b>Request ID</b></p></th>
          <th><p><b>Location</b></p></th>
          <th><p><b>Category</b></p></th>
          <th><p><b>Due Date<b></p></th>
        <% if !current_user.pilot %>
          <th><b><p data-toggle="tooltip" data-placement="top" title="Status Info">Status</b></p></th>
        <% end %>
        <%if current_user.pilot %>
          <th><p><b>Proposal sent</b></p></th>
        <% end %>
          <th colspan="6"></th>
        </tr>
      </thead>

      <tbody>
        <% @requests.each do |request| %>
          <tr>
            <td><p><%= request.id %></p></td>
            <td><p><%= request.location %></p></td>
            <td><p><%= request.category %></p></td>
            <td><p><%= request.due_date %></p></td>
            <% if !current_user.pilot %>
            <td><p><%= request.status %></p></td>
            <% end %>
            <% if !current_user.not_applied?(request) %>
              <td class="text-center"><i class="fa fa-check" aria-hidden="true"></i></td>
            <% else %>
              <td><p></p></td>
            <% end %>
            <td><div class="request-links"><%= link_to 'Show', request_path(request) %></div> </td>
            <% unless current_user.pilot || request.closed? %>
              <% if policy(request).update? %>
                <td><div class="request-links"><%= link_to 'Edit', edit_request_path(request) %></div> </td>
              <% else %>
                <td><p></p></td>
              <% end %>
              <% if policy(request).destroy? %>
                <td><div class="request-links"><%= link_to 'Cancel', request_path(request), method: :delete, data: { confirm: 'Are you sure?' } %></div> </td>
              <% else %>
                <td><p></p></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% unless current_user.pilot %>
    <div class="request-links-index green"><%= link_to 'Add Request', new_request_path %></div>
  <% end %>
   </div>
</div>

app/views/requests/new.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-6 col-md-offset-3'>
    <h1>Make a request for a Drone Pilot</h1>
    <%= render "form" %>
  </div>
</div>