config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'payments/new'

  resources :conversations do
    resources :messages
  end

  get '/profile' => 'pages#profile'
  get '/about' => 'pages#about'


  resource :operator_profiles, only: [:edit, :update, :show]
  resources :operator_profiles, only: [:show]

  resources :images, only: :destroy

  resources :requests do
    resources :proposals, only: [:create, :new]
  end

  resources :proposals, except: [:new] do
      resources :reviews
      member do
        post 'accept', to: "proposals#accept"
        post 'decline', to: "proposals#decline"
      end
      resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  def belongs_to(user)
    (sender_id == user.id) || (recipient_id == user.id)
  end

  def messages_for(user)
    messages.where.not(user_id: user.id)
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :operator_profile

  mount_uploader :image, ImageUploader

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
    belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%d/%m/%y at %l:%M %p")
  end

  def set_to_read
    self.read = true
    self.save
  end

  def self.read
    where(read: true)
  end

  def self.unread
    where(read: false)
  end

end

app/models/operator_profile.rb
class OperatorProfile < ApplicationRecord
  belongs_to :user
  has_many :videos, dependent: :destroy
  has_many :operator_skills, dependent: :destroy
  has_many :skills, through: :operator_skills
  has_many :images, dependent: :destroy

  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :images, :videos, allow_destroy: true, reject_if: :all_blank

end

app/models/operator_skill.rb
class OperatorSkill < ApplicationRecord
  belongs_to :operator_profile
  belongs_to :skill
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  belongs_to :request
  has_one :review, dependent: :destroy

  validates :price, presence: true
  validates :content, presence: true
  monetize :price_cents
  enum status: [:pending, :rejected, :accepted, :paid]
  #?
  #!
  #
  after_create :send_proposal_submitted_email

    def accept
      self.accepted!
      self.request.close
    end

    def created_by(user)
      user_id == user.id
    end


  private

    def send_proposal_submitted_email
      ProposalMailer.proposal_submitted(self).deliver_now
    end


end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy

  CATEGORIES = %w(marketing event architectural)
  validates :location, presence: true
  validates :due_date, presence: true
  validates :category, inclusion: {in: CATEGORIES}
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
  enum status: [:open, :closed]

  after_create :send_request_created_email

  def close
    self.closed!
    self.proposals.pending.each do |proposal|
      proposal.rejected!
    end
  end

  def created_by(user)
    user_id == user.id
  end

  private

  def send_request_created_email
    RequestMailer.request_created(self).deliver_now
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :proposal

  validates :content, presence: true
  validates :rating, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :operator_skills, dependent: :destroy
  validates :name, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, PhotoUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true



  has_one :operator_profile, dependent: :destroy

  has_many :requests, dependent: :destroy
  has_many :pending_proposals, through: :requests, source: :proposals #All proposals on user's requests
  has_many :proposals, dependent: :destroy #Created by this user
  has_many :messages
  has_many :created_conversations, dependent: :destroy, foreign_key: :sender_id, class_name: 'Conversation'
  has_many :joined_conversations, dependent: :destroy, foreign_key: :recipient_id, class_name: 'Conversation'
  has_many :images, through: :operator_profiles
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  after_create :send_welcome_email
  after_create :create_op_profile, if: "self.pilot?"

  def not_applied?(request)
    self.proposals.find_by(request_id: request.id).nil?
  #is there a proposal from the current_user for a specific request
  end

  def create_op_profile
    self.create_operator_profile
  end

  def unread_messages?
    Message.unread.joins(:conversation).where("(conversations.sender_id = :id OR conversations.recipient_id = :id)", id: self.id).where.not(user_id: self.id).any?
  end

  private

  def send_welcome_email
    if self.pilot?
      UserMailer.welcome_pilot(self).deliver_now
    else
      UserMailer.welcome_client(self).deliver_now
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :operator_profile

  # validates :url, presence: true
end

app/controllers/operator_profiles_controller.rb
class OperatorProfilesController < ApplicationController

  before_action :set_profile, only: [:show]
  skip_before_action :authenticate_user!, only: [:show]

  def show
  end

  def edit
    @profile =  current_user.operator_profile
    # @profile.operator_skills.build
  end

  def update
    @profile = current_user.operator_profile
    @profile.update(profile_params)
    flash[:notice] = "Your profile has been successfully updated"
    redirect_to operator_profile_path(@profile)
  end

  private

  def set_profile
    @profile = OperatorProfile.find_by(id:params[:id])
    if !current_user.operator_profile.eql?(@profile) && !current_user.pending_proposals.pluck(:user_id).include?(@profile.user_id)
      redirect_to root_path
    end
    @proposals = Proposal.where(user_id: @profile.user_id)
  end

  def profile_params
    params.require(:operator_profile).permit(:company_name, :description, :skills, {:skill_ids => []}, images_attributes: [:id, :image, :_destroy], videos_attributes: [:id, :url, :_destroy])
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/operator_profiles_helper.rb
module OperatorProfilesHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/operator_profiles/_form.html.erb
<%= simple_form_for @profile, url: operator_profiles_path, html: {multipart: true} do |f| %>
  <div class="form-inputs">

    <%= f.input :company_name, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' }%>
    <%= f.input :description, as: :text, input_html: { :class => 'form-input', rows: 4}, label_html: { :class => 'form-label' } %>
    <%= f.association :skills, as: :check_boxes, collection: Skill.all, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' } %>

    <div id="images">
      <%= f.simple_fields_for :images do |image| %>
        <%= render 'image_fields', f: image %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add image', f, :images %>
      </div>
    </div>

    <div class="form-label">Videos</div>
    <div id="videos">
      <%= f.simple_fields_for :videos do |url| %>
        <%= render 'video_fields', f: url %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add url', f, :videos %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'form-btn'%>
  </div>
<% end %>

app/views/operator_profiles/_image_fields.html.erb
  <div class="nested-fields">
    <% if f.object.persisted? %>
      <%= cl_image_tag f.object.image.url, :width=>150, :height=>150, :crop=>"thumb" %>
      <div class="links-sm">
        <%= link_to_remove_association "remove image", f %>
      </div>
    <% else %>
      <%= f.input :image, input_html: { :class => 'form-input'}, label_html: { :class => 'form-label' } %>
      <div class="links-sm">
        <%= link_to_remove_association "remove uploader", f %>
      </div>
    <% end %>
  </div>

app/views/operator_profiles/_video_fields.html.erb
  <div class="nested-fields">
    <%= f.input :url, input_html: { :class => 'form-input', rows: 4}, label_html: { :class => 'form-label' } %>
    <div class="links-sm">
      <%= link_to_remove_association "remove url", f %>
    </div>
  </div>

app/views/operator_profiles/edit.html.erb
<div class="container">
  <div class='col-xs-12 col-md-6 col-md-offset-3 footer-container'>
    <div class="form">
    <h1>Create your Profile here!</h1>
    <p>You can edit your profile here.</p>
    <p>Remember: Showcase your skills and get drone jobs</p>
    <%= render "form" %>
    </div>
  </div>
</div>

app/views/operator_profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs-12 col-md-6 col-md-offset-3 footer-container'>
    <div class="form">
      <h1>Create a new pilot profile</h1>
      <p>Showcase your best work and convince customers!</p>
      <%= render "form" %>
    </div>
    </div>
  </div>
</div>

app/views/operator_profiles/show.html.erb
<div class="container">
<div class="row">
    <div class='col-xs-12 col-md-4'>
      <figure class="oprofile-box ">
        <% if !@profile.images.first.nil? %>
          <%= cl_image_tag @profile.images.first.image %>
        <% else %>
          <%= image_tag "placeholder.jpg" %>
        <% end %>
        <figcaption>
        <% if !@profile.user.avatar.url.nil? %>
          <%= cl_image_tag @profile.user.avatar.url(:standard), class:"profile" %>
        <% end %>
          <h2><span><%= @profile.company_name %></span></h2>
          <h3>Skills</h3>
          <% @profile.skills.each do |s| %>
          <ul>
            <li><p><%= s.name %></p></li>
          </ul>
          <% end %>
        <% if policy(@profile).update? %>
          <%= link_to 'Edit Profile', edit_operator_profiles_path %></p>
        <% end %>
          <p><a href="javascript:history.back()">Go Back</a></p>
        </figcaption>
      </figure>
    </div>

    <div class='col-xs-12 col-md-8'>
      <% if @profile.videos.first %>
        <div class="embed-container">
          <p><%= embed(@profile.videos.first.url) %></p>
        </div>
      <% end %>

      <div class="description-box">
        <h3>About us</h3>
        <p><%= @profile.description %></p>
      </div>

      <div class="image-container">
        <% @profile.images.each do |p| %>
          <% if @profile.images %>
            <div class="col-xs-12 col-md-4">
              <%= link_to asset_path(p.image.url(:standard)), :class => "swipebox" do %>
                <%= cl_image_tag p.image.url(:standard), class: "gallerypictures" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="row">
      <div class="review col-xs-12 col-md-12">
      <h3>Reviews</h3>
          <% @proposals.each do |proposal| %>
            <% unless proposal.review == nil %>
              <p><b>Review by <%= User.find_by(id:proposal.request.user_id).first_name %> <%= User.find_by(id:proposal.request.user_id).last_name %> - <%= proposal.review.created_at.strftime("%d %b %H:%M") %></b></p>
              <p><%= proposal.review.content %></p>
              <p><% (proposal.review.rating).times do %>
                <i class="fa fa-star" aria-hidden="true"></i>
              <% end %>
                <% (5-(proposal.review.rating)).times do %>
                <i class="fa fa-star-o" aria-hidden="true"></i>
              <% end %>

              </p>
            <% end %>
          <% end %>
        </div>
        </div>
       </div>
  </div>
</div>




<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->


<!-- javascript -->
<% content_for(:after_js) do %>
  <%= javascript_tag do %>

$(document).scroll(function() {
    checkOffset();
});
function checkOffset() {
    if($('.oprofile-box').offset().top + $('.oprofile-box').height()
                                           >= $('#footer').offset().top -10)
        $('.oprofile-box').css('position', 'absolute');
    if($(document).scrollTop() + window.innerHeight < $('#footer').offset().top)
        $('.oprofile-box').css('position', 'fixed'); // restore when you scroll up
}

(function( $ ) {

  $( '.swipebox' ).swipebox();

} )( jQuery );


  <% end %>
<% end %>