config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'payments/new'

  resources :conversations do
    resources :messages
  end

  get '/profile' => 'pages#profile'
  get '/about' => 'pages#about'


  resource :operator_profiles, only: [:edit, :update, :show]
  resources :operator_profiles, only: [:show]

  resources :images, only: :destroy

  resources :requests do
    resources :proposals, only: [:create, :new]
  end

  resources :proposals, except: [:new] do
      resources :reviews
      member do
        post 'accept', to: "proposals#accept"
        post 'decline', to: "proposals#decline"
      end
      resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#index"
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  belongs_to :request
  has_one :review, dependent: :destroy

  validates :price, presence: true
  validates :content, presence: true
  monetize :price_cents
  enum status: [:pending, :rejected, :accepted, :paid]
  #?
  #!
  #
  after_create :send_proposal_submitted_email

    def accept
      self.accepted!
      self.request.close
    end

    def created_by(user)
      user_id == user.id
    end


  private

    def send_proposal_submitted_email
      ProposalMailer.proposal_submitted(self).deliver_now
    end


end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, except: [:accept, :show]
  before_action :set_request, only: [:new, :create]

  def index
    if current_user.pilot
      @proposals = current_user.proposals
    else
      redirect_to root_path
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
    redirect_to root_path if !@proposal.created_by(current_user) && !@proposal.request.created_by(current_user)
  end

  def new
    @proposal = current_user.proposals.new()
  end

  def create
    @proposal = @request.proposals.build(proposal_params)
    @proposal.user = current_user
    @proposal.save
    flash[:notice] = "Your proposal has been created"
    redirect_to proposal_path(@proposal)
  end

  def update
    @proposal.update(proposal_params)
    redirect_to proposal_path(@proposal)
  end

  def destroy
    @proposal.destroy
    redirect_to proposals_path
  end

  def accept
    proposal = Proposal.find_by(id:params[:id])
    if proposal && proposal.request.user_id == current_user.id
      proposal.accept
      redirect_to proposal_path(proposal)
    else
      redirect_to root_path
    end
  end

  def decline
    @proposal = Proposal.pending.find_by(id:params[:id])
    @proposal.rejected!
    redirect_to proposal_path(@proposal)
  end

private

  def set_request
    @request = Request.find(params[:request_id])
  end

  def set_proposal
    if current_user
      @proposal = current_user.proposals.find_by(id: params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  # Only allow a trusted parameter "white list" through.
  def proposal_params
    params.require(:proposal).permit(:date, :price, :content, :status)
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= simple_form_for [@request, @proposal] do |f| %>
  <div class="form-inputs">
    <%#= f.input :date, required: true, autofocus: true, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' } %>
    <% if @proposal.new_record? %>
      <%= f.input :date, as: :hidden, input_html: { :value => @request.due_date, :class => 'form-input' }, label_html: { :class => 'form-label' } %>
     <% end %>
    <%= f.input :price, label:"Price in USD", required: true, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' } %>
    <%= f.input :content, as: :text, label: "Message", input_html: { :class => 'form-input', rows: 4}, label_html: { :class => 'form-label' } %>
    <%= f.input :request_id, as: :hidden, input_html: {value: params[:request_id]}, input_html: { :class => 'form-input' }, label_html: { :class => 'form-label' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'form-btn' %>
  </div>
<% end %>

app/views/proposals/_proposal.html.erb
<!-- List of all Proposals-->

  <div class="proposals">
  <h2 class="proposal-list text-center">List of all Proposals</h2>
  <% if @request.proposals.empty? %>
  <p> You have no proposals yet </p>
  <% else %>

  <% @request.proposals.each do |proposal| %>

    <div class="col-md-3 col-xs-6">
      <figure class="proposal-box">
        <%= link_to proposal_path(proposal.id) do %>
        <% if !proposal.user.operator_profile.images.first.nil? %>
          <%= cl_image_tag proposal.user.operator_profile.images.first.image %>
        <% else %>
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample87.jpg" alt="sample87" />
        <% end %>
      <figcaption>
      <% if !proposal.user.avatar.url.nil? %>
        <%= cl_image_tag proposal.user.avatar.url(:standard), class:"profile" %>
      <% end %>
        <h2><%= proposal.user.operator_profile.company_name %></h2>
        <p><%= humanized_money_with_symbol(proposal.price) %></p>
        <div class="proposal-box-status">
          <% if proposal.accepted? %>
            <p><i class="fa fa-check" aria-hidden="true"></i> Accepted!</p>
          <% elsif proposal.pending? %>
            <p><i class="fa fa-question" aria-hidden="true"></i> Pending</p>
          <% elsif proposal.rejected? %>
           <p><i class="fa fa-times" aria-hidden="true"></i> Declined!</p>
          <% elsif proposal.paid? %>
           <p><i class="fa fa-check" aria-hidden="true"></i> Paid!</p>
          <% end %>
        </div>
      </figcaption>
      <% end %>
      </figure>
    </div>

    <% end %>
  <% end %>
 </div>

app/views/proposals/edit.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-6 col-md-offset-3 footer-container'>
    <div class="form">
      <h1>Edit your proposal</h1>
      <%= render "form" %>
  </div>
  </div>
</div>

app/views/proposals/index.html.erb
<div class="container">
  <div class="proposal-summary footer-container">
      <h1>These are your proposals</h1>
      <p>Manage your proposals here</p>

  <table class= "table table-hover ">
    <thead>
      <tr>
        <th>Location</th>
        <th>Date</th>
        <th>Price</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @proposals.each do |proposal| %>
        <tr>
          <td><p><%= proposal.request.location %></p></td>
          <td><p><%= proposal.date %></p></td>
          <td><p><%= humanized_money_with_symbol(proposal.price) %></p></td>
          <td><p><%= proposal.status %></p></td>
          <td><div class="proposal-links"><%= link_to 'Show', proposal_path(proposal) %></div> </td>
        <% if current_user.pilot? && proposal.pending? %>
          <td><div class="proposal-links"><%= link_to 'Cancel', proposal_path(proposal), method: :delete, data: { confirm: 'Are you sure?' } %> </td></div>
        <% else %>
          <td><p></p></td>
        <% end %>
        <% unless current_user.pilot? %>
          <td><div class="proposal-links"><%= link_to 'Add review', new_proposal_review_path(request) %></div>
          </td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <td><div class="proposal-links"><%= link_to 'Back to requets', requests_path %> </div></td>
  </div>
</div>

app/views/proposals/new.html.erb
<div class="container">
  <div class='col-xs-12 col-md-6 col-md-offset-3 footer-container'>
    <div class="form">
      <h1>Make a Proposal for <%= User.find_by(id:@request.user_id).first_name %> <%= User.find_by(id:@request.user_id).last_name %></h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/proposals/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs-12 col-md-6 col-md-offset-3 footer-container'>
      <div class="proposal-summary">
        <h1>Proposal Summary</h1>
        <p>Find the Proposal Details here:</p>
          <figure class="proposal-box">
            <% if !@proposal.user.operator_profile.images.first.nil? %>
              <%= link_to operator_profile_path(@proposal.user.operator_profile) do %>
                <%= cl_image_tag @proposal.user.operator_profile.images.first.image %>
              <% end %>
            <% else %>
              <%= link_to operator_profile_path(@proposal.user.operator_profile) do %>
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample87.jpg" alt="sample87" />
              <% end %>
            <% end %>
            <figcaption>
              <% if !@proposal.user.avatar.url.nil? %>
                <%= cl_image_tag @proposal.user.avatar.url(:standard), class:"profile" %>
              <% end %>
                <h2><%= @proposal.user.operator_profile.company_name %></h2>
                <p><b>Total Price: </b><%= humanized_money_with_symbol(@proposal.price) %></p>
                <p><b>Additional Info: </b><%= @proposal.content %></p>
                <p><%= link_to 'See Profile', operator_profile_path(@proposal.user.operator_profile) %></p>
              <% if current_user.pilot? && @proposal.pending? %>
                <p><%= link_to 'Cancel proposal', proposal_path(@proposal), method: :delete, data: { confirm: 'Are you sure?' } %> <%= link_to 'Edit proposal', edit_proposal_path(@proposal) %></p>
              <% end %>
              <% if !current_user.pilot? && @proposal.pending? %>
                <%= link_to 'Accept!', accept_proposal_path(@proposal), class: 'btn btn-success', method: :post, data: { confirm: 'Are you sure?' } %>
                <%= link_to 'Decline!', decline_proposal_path(@proposal), class: 'btn btn-danger', method: :post, data: { confirm: 'Are you sure?' } %>
              <% end %>

              <% if @proposal.accepted? && !current_user.pilot? %>
                  <p>Pay your booking now</p>
                    <%= form_tag proposal_payments_path(@proposal) do %>
                      <article>
                        <label class="amount">
                          <span>Amount: <%= humanized_money_with_symbol(@proposal.price) %></span>
                        </label>
                      </article>

                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-email="<%= current_user.email %>"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-name="Drone Job"
                        data-description="Proposal by  <%= @proposal.user.operator_profile.company_name %>"
                        data-amount="<%= @proposal.price_cents %>"
                        data-currency="usd">
                      </script>
                    <% end %>
                  <p><%= link_to "Message user", conversations_path(sender_id: current_user.id, recipient_id: @proposal.user.id), method: 'post' %></p>
              <% elsif @proposal.accepted? %>
                <div class="accepted">
                  <p class="green"><b>This proposal has been accepted!</b></p>
                </div>
              <% elsif @proposal.rejected? %>
                <div class="declined">
                  <p class="red"><b>This proposal has been declined!</b></p>
                </div>
              <% elsif @proposal.paid? && !current_user.pilot? %>
                <div class="accepted">
                  <p><b>This proposal has been paid!</b></p>
                  <p><%= link_to 'Add review', new_proposal_review_path(@proposal) %>
                  <%= link_to "Message user", conversations_path(sender_id: current_user.id, recipient_id: @proposal.user.id), method: 'post' %></p>
                </div>
              <% elsif @proposal.paid? && current_user.pilot? %>
                <div class="accepted">
                  <p class="green"><b>This proposal has been paid!</b></p>
                </div>
              <% end %>

              <% if !current_user.pilot? %>
                <p><a href="javascript:history.back()">Go Back</a></p>
              <% end %>
              <% if current_user.pilot? %>
                <p><%= link_to 'Back to all proposals', proposals_path %></p>
              <% end %>
            </figcaption>
          </figure>
      </div>
    </div>
  </div>
</div>